services:
  db:
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_webapp
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
  tomee:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
volumes:
  db: